// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    partial class TravelApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Frankfurt",
                            Description = "Woolly Mammoth",
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "Portland",
                            Description = "Dinosaur",
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Seattle",
                            Description = "Dinosaur",
                            Rating = 3
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Cairo",
                            Description = "Woolly Mammoth",
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Austin",
                            Description = "Dinosaur",
                            Rating = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
